version: "3.9"

services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  node_backend:
    image: your-dockerhub-username/node-backend:latest
    container_name: node_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres_db:5432/mydb
    depends_on:
      - postgres_db

  vite_frontend:
    image: your-dockerhub-username/vite-frontend:latest
    container_name: vite_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - node_backend

volumes:
  postgres_data:
