# version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: node_backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8101:8101"
    depends_on:
      - postgres
    command: >
      sh -c "npx prisma migrate deploy && npm run start"

  frontend:
    build: ./frontend
    container_name: vite_frontend
    restart: always
    ports:
      - "3039:3039"
    depends_on:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  

