# version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: vite_frontend
    restart: always
    ports:
      - "3039:3039"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev -- --host 0.0.0.0

  # backend:
  #   build: ./backend
  #   container_name: node_backend
  #   restart: always
  #   ports:
  #     - "8101:8101"
  #   env_file:
  #     - ./backend/.env
  #   depends_on:
  #     - postgres
  #   command: sh -c "npx prisma migrate deploy && npm run dev"
  #   volumes:
  #     - ./backend:/usr/src/app
  #     - /usr/src/app/node_modules
  # backend:
  #   build: ./backend
  #   container_name: node_backend
  #   restart: always
  #   ports:
  #     - "8101:8101"
  #   # 👇 Add this line to load the .env file
  #   env_file:
  #     - ./backend/.env
  #   depends_on:
  #     - postgres
  #   # No command or volumes needed; the Dockerfile handles everything
  backend:
    build: ./backend
    container_name: node_backend
    restart: always
    ports:
      - "8101:8101"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    # These keys enable development features
    command: sh -c "npx prisma migrate deploy && npm run dev"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
      POSTGRES_PORT: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      
    depends_on:
      - postgres

volumes:
  postgres_data:
